name: output-event-issues

on:
  issues:
    types: [opened, edited]

jobs:
  debug-output-event-issues:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG - Display json object
        run: |
  output-event-issues:
      - name: Output issue event
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Issue URL: ${{ github.event.issue.html_url }}"
          echo "Issue State: ${{ github.event.issue.state }}"
          echo "Issue Labels: ${{ toJson(github.event.issue.labels) }}"
          echo "Issue Assignee: ${{